version: "3.9"
services:
  hyrsm: 
    build:
      context: .
      dockerfile: docker/hyrsm/Dockerfile
    image: prediction-research/hyrsm

    ipc: host
    tty: true
    user: ${FIXUID:?}:${FIXGID:?}

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  hyrsmplusplus: 
    build:
      context: .
      dockerfile: docker/hyrsmplusplus/Dockerfile
    image: prediction-research/hyrsmplusplus

    ipc: host
    tty: true
    user: ${FIXUID:?}:${FIXGID:?}

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  pgp: 
    build:
      context: .
      dockerfile: docker/pgp/Dockerfile
    image: prediction-research/pgp

    ipc: host
    tty: true
    user: ${FIXUID:?}:${FIXGID:?}

    volumes:
      - ./src/PGP/:/home/docker/pgp/
      - /mnt/scratch/nuscenes_CLEAN:/nuscenes_CLEAN:ro
      - /mnt/scratch/nuscenes_PGP_PREPROCESS:/nuscenes_PGP_PREPROCESS
      - /mnt/scratch/PGP_lr-scheduler.tar:/PGP_lr-scheduler.tar:ro
      - /mnt/scratch/pgp_output:/pgp_output

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0'] # Change to ['0', '1'] to use two GPUs
            capabilities: [gpu]

  
            